name: Sync and Build Repo B

on:
  push:
    branches:
      - main  # Trigger when Repo A updates

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Quartz
        uses: actions/checkout@v4
        with:
          repository: jackyzha0/quartz

      - name: Remove default content
        run: |
          rm -rf content
          rm -rf .github

      - name: Checkout Vault
        uses: actions/checkout@v4
        with:
          path: content

      - name: Copy quartz changes
        run: |
          mv content/.quartz/quartz.config.ts ./quartz.config.ts
          cat ./quartz/styles/custom.scss
          cp -r content/.quartz/styles ./quartz/styles
          echo "new changes"
          cat ./quartz/styles/custom.scss

      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
